project_id = "dikgmythsvmdbdpjdjmc"

[functions.cannapag-webhook]
verify_jwt = false

[functions.chat-ai]
verify_jwt = true

[functions.add-brevo-contact]
verify_jwt = false

[functions.process-document]
verify_jwt = true

[functions.process-structured-document]
verify_jwt = true

[functions.parse-pdf]
verify_jwt = true

[functions.document-status]
verify_jwt = true

[functions.rag-ask]
verify_jwt = true

[functions.rag-advanced]
verify_jwt = true

[functions.analyze-image]
verify_jwt = true