project_id = "dikgmythsvmdbdpjdjmc"

[functions.chat-ai]
verify_jwt = true

[functions.add-brevo-contact]
verify_jwt = false

[functions.process-document]
verify_jwt = true

[functions.send-cancellation-email]
verify_jwt = false

[functions.finalize-cancellations]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.validate-signup]
verify_jwt = false

[functions.revert-cancellation]
verify_jwt = true

[functions.request-cancellation]
verify_jwt = true

[functions.activate-specialist]
verify_jwt = true

[functions.create-portal-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.sync-stripe-subscription]
verify_jwt = false